### ISSUE TITLE
Remove "Read More" button for events that don't need it

### ISSUE THREAD

**Issue by kirahowe** [pitonneux/website#1]
Right now it is shown even if the event description is short enough not to need truncating:

![screen shot 2016-06-19 at 7 41 58 pm](https://cloud.githubusercontent.com/assets/11531673/16180539/fe4fc122-3655-11e6-99f2-b0c1ea6fa6e0.png)

It shouldn't be there for events with short descriptions

**Comment by deniselhirondelle** [comment]
Working on making something like [this](//stackoverflow.com/questions/4571813/why-is-this-javascript-function-so-slow-on-firefox) work. Also have a lazy way that won't display the button at less than 200 characters. JS would be best though.

**Comment by kirahowe** [comment]
Awesome, thanks Denise! Actually just not showing the button when the text is less than the truncated length works, too. We could also consider not showing any event descriptions on the home page at all and instead just give each their own page with the full description. Actually maybe that would fit better with Curtis' design.. what do you think? .. just thinking out loud.

**Comment by deniselhirondelle** [comment]
You have a good point about matching the design. Plus, event keywords (e.g. "programming events in montreal in august") should be ranked higher if they have their own page. Anyone looking specifically for an event should be taken straight to the events themselves by Google, skipping all the intro stuff that they know already.

I'd go for that. You?

**Comment by kirahowe** [comment]
That's a great point. Let's do that. Maybe we can still show 2 or 3 "featured" events on the homepage, but just the titles and a "find out more" button or something. Either way I think the "read more" button that expands to show the full text is out. I'll write a story for creating a `#show` for events instead, and then we can make those pages look nice! I guess they will also be accessible to guests, and maybe a button at the bottom to edit the event if the user is an admin.

**Comment by kirahowe** [comment]
Given this, I'm going to close this issue and point to #12. We'll move forward with a page for each event and just links on the home page directly to the featured events.

**Comment by deniselhirondelle** [comment]
Sounds good.
