### ISSUE TITLE
Make 404 and 5xx pages nice

### ISSUE THREAD

**Issue by kirahowe** [pitonneux/website#22]
Instead of the standard ugly ones. These are found in:

```
public/404.html
public/422.html
public/500.html
```

Styles have to be inlined so it can be simple but they should look similar to the rest of the app with a friendly message.

**Comment by 256k** [comment]
i'd like to take this one over and give it a shot :)

**Comment by kirahowe** [comment]
Awesome! Thanks so much.

**Comment by 256k** [comment]
this should probably get its labels updated. i dont know how to do that.

**Comment by kirahowe** [comment]
Good call! Thanks Fayek. I forgot to close this when I merged your branch. Thanks for the great work :)

**Comment by kirahowe** [comment]
Closed with PR #31
