### ISSUE TITLE
Clicking the header logo ruins the smooth scrolling

### ISSUE THREAD

**Issue by kirahowe** [pitonneux/website#8]
To reproduce:
- visit the homepage
- click on one of the nav links
- see how the scrolling is nice and smooth
- click on the coffee cup to go back to the top
- click on one of the nav links
- see how the page just jumps now, doesn't scroll anymore

The scrolling should always be smooth not choppy.

**Comment by deniselhirondelle** [comment]
Fixed in my fork.

**Comment by kirahowe** [comment]
Woohoo! Thanks Denise :) Go ahead an open a pull request for the changes.

**Comment by kirahowe** [comment]
This is closed by PR #14.
